Edit explanation for guidance hint & mandatory response
kobotoolbox/docs pull request #189
Opened 2022-01-21 09:09 UTC by exprin

2022-01-21 09:11 UTC, exprin commented
Hi @joshuaberetta, I have made some minor changes to this article especially on the explanation for guidance hint and mandatory response. I just thought it's something you should be able to quickly review and commit.

2022-01-21 18:14 UTC, joshuaberetta requested changes

2022-01-21 18:14 UTC, joshuaberetta commented on source/question_options.md
> +Guidance hints can be used as internal notes when collaborating with others in developing the form. You can also show them on printouts or during training for enumerators.
It seems we are confusing the difference between the regular [`hint`](https://xlsform.org/en/#regular-hints) and [`guidance_hint`](https://xlsform.org/en/#guidance-hints) here now. This is the difference in how the user or enumerator will see them:
<img width="532" alt="hint" src="https://user-images.githubusercontent.com/50016008/150577542-25bf1639-02e4-4062-94be-12195f41d5ab.png">

I would suggest being explicit about which type of hint you are referring to and maybe include an XLSForm survey example such as this to exemplify the difference:

**survey**

| type | name | label              | hint           | guidance_hint           |
| ---  | ---  | ---                | ---            | ---                     |
| text | name | What is your name? | This is a hint | This is a guidance hint |

2022-01-21 18:14 UTC, joshuaberetta commented on source/question_options.md
> +This settings allows you to specify whether the question must be responded to at all times or not.
Maybe just note that this is equivalent to the `required` field in XLSForm and link to the docs: https://xlsform.org/en/#required

2022-01-21 18:14 UTC, joshuaberetta commented on source/question_options.md
> +1. Yes - The question must be answered at all times. If the user does not provide a response, he/she will not be able to move to the next question or save the form.
Use "they" rather than "he/she"

2022-01-21 18:14 UTC, joshuaberetta commented on source/question_options.md
> +3. Custom logic - You can define logic using XLSForm code which will define when the question will be mandatory. For example, if you set the following custom logic `age > 18`, the question will be ma
This would need to be `${age} > 18`

2022-01-21 18:22 UTC, exprin commented
Thanks so much for the comments @joshuaberetta. It seems I jumped the gun on several things, I really appreciate the direction. I will quickly work on the changes and resubmit

2022-02-24 16:57 UTC, exprin commented
Hi @joshuaberetta, I have added a new commit to this article addressing the issues you mentioned and expanding it further. Please check.

2022-03-08 23:56 UTC, joshuaberetta approved these changes

2022-03-08 23:56 UTC, merged