New article: GPS Question types
kobotoolbox/docs pull request #281
Opened 2022-07-13 12:42 UTC by exprin

@joshuaberetta, please review this article

2022-07-19 16:58 UTC, joshuaberetta requested changes

2022-07-19 16:58 UTC, joshuaberetta commented on source/gps_questions.md
> +question type and the `area()` function in the formbuilder as shown below:
Rather something like:
> You can calculate an area using the "Calculate" question type and the [`area()`](https://docs.getodk.org/form-operators-functions/#area) method, as shown below:

2022-07-19 16:58 UTC, joshuaberetta commented on source/gps_questions.md
> +In the example above, the question “Capture the GPS of the boundaries” has been
Please update “Capture the GPS of the boundaries” as discussed above

2022-07-19 16:58 UTC, joshuaberetta commented on source/gps_questions.md
> +settings has been changed to “boundary”.
You don't need to say "changed" as you are setting up the form from scratch and this implies that it was set to something else before and now you are making it something else. Rather use a word like "set" or just "the value is X".

2022-07-19 16:58 UTC, joshuaberetta commented on source/gps_questions.md
> +the calculation will be in square meters.
Please refer to my comment earlier about the `distance()` method.

2022-07-19 16:58 UTC, joshuaberetta commented on source/gps_questions.md
> +displaying the calculated area on the form.
Refer to earlier comment on the same sentence.

2022-07-19 16:58 UTC, joshuaberetta commented on source/gps_questions.md
> +| note      | display_area | The distance is ${area} Square Meters |                   |
Rather "square meters"

2022-07-19 16:58 UTC, joshuaberetta commented on source/gps_questions.md
> +  Download an XLSForm with examples from this article
> You can download an XLSForm...

2022-07-27 12:47 UTC, exprin commented on source/gps_questions.md
> +KoboToolbox allows you to collect GPS coordinates as part of your data
I have rephrased this.

2022-07-27 12:50 UTC, exprin commented on source/gps_questions.md
> +feature on the earth’s surface such as a house, or a borehole.
I have removed that part

2022-07-27 14:42 UTC, exprin commented
@joshuaberetta I just added a commit to this. Please review

2022-07-30 12:28 UTC, joshuaberetta approved these changes
@exprin please review the edits I made before merging.

2022-07-30 12:28 UTC, merged