New article: Barcode/QRCode questions
kobotoolbox/docs pull request #282
Opened 2022-07-13 13:44 UTC by exprin

@joshuaberetta Please review this article for me

2022-07-20 07:00 UTC, joshuaberetta requested changes

2022-09-30 05:11 UTC, exprin commented on source/barcode_qrcode_questions.md
> +following:
Good point.

2022-09-30 05:20 UTC, exprin commented on source/barcode_qrcode_questions.md
> +[automatically populate fields from a csv attached to your project, or a different form project](https://community.kobotoolbox.org/t/trying-to-build-a-form-that-will-use-pulldata-function-to-verify-b
Done!

2022-09-30 05:20 UTC, exprin commented on source/barcode_qrcode_questions.md
> +### Setting up in FormBuilder
done

2022-09-30 05:20 UTC, exprin commented on source/barcode_qrcode_questions.md
> +To add a barcode/QR code question:
done!

2022-09-30 05:21 UTC, exprin commented on source/barcode_qrcode_questions.md
> +- In the KoboToolbox Formbuilder, click the <i class="k-icon k-icon-plus"></i>
DOne

2022-09-30 05:21 UTC, exprin commented on source/barcode_qrcode_questions.md
> +### Setting up in xlsform
Done!

2022-09-30 05:22 UTC, exprin commented on source/barcode_qrcode_questions.md
> +To add a barcode question in XLSform, add a question with type `barcode` as
Done!

2022-09-30 05:22 UTC, exprin commented on source/barcode_qrcode_questions.md
> +## How barcode/qr code questions are displayed on web forms and KoboCollect
Fixed

2022-09-30 05:23 UTC, exprin commented on source/barcode_qrcode_questions.md
> +type “front” in the Appearance(Advanced) box
Done

2022-09-30 05:24 UTC, exprin commented on source/barcode_qrcode_questions.md
> +In XLSForm, you can set the default camera for capturing the QR/Barcode to be
Sorted

2022-09-30 05:24 UTC, exprin commented on source/barcode_qrcode_questions.md
> +the front (selfie) camera by typing ‘front’ in the appearance column as follows:
Done!

2022-10-18 16:29 UTC, joshuaberetta requested changes
@exprin, I've made some minor edits. Once you update the KoboCollect image I'll merge 🙂

2025-06-18 12:17 UTC, salomegarnier commented
@exprin could you update the KoboCollect image + change the header size for "Default appearance" to a lower size? Then it'll be ready to merge

2025-06-18 14:29 UTC, merged