Added limitations on numeric qtypes
kobotoolbox/docs pull request #289
Opened 2022-07-27 12:40 UTC by exprin

I added the following:

- Explanation of limitations of number and decimal question types
- How to add number, range, and decimal question types in XLSForm
- a downloadable CLSForm

@joshuaberetta kindly review

2022-07-30 10:15 UTC, joshuaberetta requested changes
@exprin, is there a reason why the two files:
- source/images/pulling_data_excelquery/excel_data_source_settings.gif
- source/images/pulling_data_excelquery/excel_load_table.gif
Are included in this PR?

2022-07-30 13:02 UTC, exprin commented
> @exprin, is there a reason why the two files:
> 
> * source/images/pulling_data_excelquery/excel_data_source_settings.gif
> * source/images/pulling_data_excelquery/excel_load_table.gif
>   Are included in this PR?

I might have accidentally added the "Pulling data into Power Query" files into master instead of creating a new branch. SO now those files are moving with me to every branch. I must have added them to the commit for this branch accidentally

2022-07-30 13:03 UTC, exprin commented on source/number_decimal_range.md
> +| range   | star_rating     | Rate the effectiveness of the project from 1 to 5        | rating        | tart=1 end=5 step=1  |
Done

2022-07-30 13:04 UTC, exprin commented on source/number_decimal_range.md
> +Note: When adding a `range` question to an xlsform, the start, end and step parameters are added in the `parameters` column.
Done

2022-07-30 13:04 UTC, exprin commented on source/number_decimal_range.md
> +  Negative signs and decimal points count towards the character limit.
Yes I tested this both on Enketo and Collect

2022-07-30 13:10 UTC, exprin commented
@joshuaberetta I have sent a commit to this branch resolving the comments

2022-07-31 15:53 UTC, joshuaberetta approved these changes
@exprin please review the changes I made before merging.

2022-07-31 15:53 UTC, merged