Update managing_permissions.md
kobotoolbox/docs pull request #355
Opened 2024-01-23 20:17 UTC by maedelange

2024-01-24 20:57 UTC, noliveleger commented on source/managing_permissions.md
> +- Select "Allow web submissions to this form without a username and password"
`web` could removed (according to loom video).

2024-01-24 20:57 UTC, noliveleger commented on source/managing_permissions.md
> +You can also access this by going to the **Sharing** tab in the **SETTINGS** page in your data collection project and toggling between the default setting to “Allow web submissions to this form witho
same here . remove `web` in web submissions.

2024-02-04 09:51 UTC, exprin requested changes

2024-02-04 09:51 UTC, exprin commented on source/managing_permissions.md
>  ![Requiring passwords](images/managing_permissions/requiring_passwords.gif)
![Permissions](https://github.com/kobotoolbox/docs/assets/92011614/b088cf47-0672-447a-848f-d635eeef7020)

2024-02-04 09:51 UTC, exprin commented on source/managing_permissions.md
> +- Go to **Collect data** inside your KoboToolbox account
- Open the project in KoboToolbox, and go to the FORM section

2024-02-04 09:51 UTC, exprin commented on source/managing_permissions.md
> +- Use the toggle button to enable "Allow submissions to this form without a username and password"
- Below the Collect Data section, use the toggle button to enable "Allow submissions to this form without a username and password"

2024-02-04 09:51 UTC, exprin commented on source/managing_permissions.md
> +
![Sharing settings](https://github.com/kobotoolbox/docs/assets/92011614/ba200e90-d334-49fc-bbb8-578e680cd3c2)

2024-02-06 03:13 UTC, merged