Closing #46 - Minor updates
kobotoolbox/docs pull request #48
Opened 2021-02-16 15:54 UTC by Kalyan-Lama

* Formatting
* Update images

2021-02-18 00:21 UTC, joshuaberetta requested changes

2021-02-18 00:21 UTC, joshuaberetta commented on source/api.md
> +   ![image](/images/api/token2.png)
Seems these two images haven't been checked into the repo

2021-02-18 00:21 UTC, joshuaberetta commented on source/api.md
> +### Getting your API Token:
You could add a third method if you like doing the following using `curl`:

```bash
curl -u username:password "https:/[kpi-url]/token/?format=json"
```

2021-02-18 00:21 UTC, joshuaberetta commented on source/api.md
> +### Testing your API:
Make sure to put code within back ticks:

```bash
curl -X GET https://[kpi-url]/api/v2/assets.json -H "Authorization: Token [your_token_goes_here]"
```

2021-02-18 00:27 UTC, joshuaberetta commented on source/api.md
> +   ![image](/images/api/token2.png)
Just saw that you added them in the other branch 😄

2021-02-25 09:40 UTC, Kalyan-Lama commented
Thank you, @joshuaberetta. Your advice was constructive. Have updated as advised. Maybe we could now merge this with the master branch.

2021-02-26 00:51 UTC, merged