Closing # 87 - updated formatting, contents and images
kobotoolbox/docs pull request #88
Opened 2021-07-05 13:34 UTC by Kalyan-Lama

2021-07-05 13:36 UTC, Kalyan-Lama commented
@joshuaberetta, I have updated this support article. Could you kindly review and merge them with the master branch? cc: @tinok

2021-07-09 18:03 UTC, joshuaberetta requested changes

2021-07-09 18:03 UTC, joshuaberetta commented on source/pulling_data_into_excelquery.md
> +Once you have synced your KoBoToolbox with your Microsoft Excel through __Excel Power Query__, you should be able to have the dataset in Microsoft Excel. However, when the KoBoToolbox server is updat
You can rephrase this to something like:

> Once you have synced KoBoToolbox with Excel through __Excel Power Query__, you should have the dataset stored locally. However, when the dataset on the server updates (i.e. through new submissions, deletions, amendments), your local dataset does not automatically update. To resync your data, you will need to click the __Data__ button and then __Refresh All__.

2021-08-19 20:09 UTC, joshuaberetta approved these changes

2021-08-19 20:09 UTC, merged